import type { Metadata } from "next";
import "./globals.css";
import { satoshiFont } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" className={`${satoshiFont.variable} antialiased`}>
      <body>{children}</body>
    </html>
  );
}
